#!/usr/bin/env python3
"""Third-party license inventory for the Rust workspace.

Reads `cargo metadata --locked` and writes THIRD-PARTY.md: every crate in
Cargo.lock outside the workspace, with its version, license expression and
source. Where a crate's terms require carrying a notice in binary
distributions (a group of alternatives with no Apache-2.0, Unlicense, CC0 or
MIT-0 option, or a mandatory AND clause such as Unicode-3.0), the text of
its license files follows the table. Rook takes every crate under the
Apache-2.0 option when one is offered.

A crate whose license expression is missing, or names a license outside
ALLOWED, is refused, so a new dependency with unfamiliar terms fails the
gate instead of shipping. Non-cargo third parties (the vendored Open-RMF
sources and what the prebuilt cell links) are recorded by hand in NOTICE.

Usage: third_party.py            rewrite THIRD-PARTY.md
       third_party.py --check    exit 1 if THIRD-PARTY.md is stale
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD-PARTY.md"

# Every license a dependency may be offered under. Anything else refuses.
ALLOWED = {
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MIT-0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Unlicense",
    "0BSD",
}

# Options that carry no notice obligation for a binary distribution, given
# that the Apache-2.0 text ships as LICENSE and no crate ships a NOTICE file
# (the script checks that below).
NOTICE_FREE = {
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unlicense",
    "CC0-1.0",
    "MIT-0",
    "0BSD",
}

LICENSE_FILE = re.compile(r"^(LICEN[CS]E|COPYING|NOTICE|UNLICENSE)", re.IGNORECASE)


def canonical(expression: str) -> str:
    """Rewrites Cargo's legacy `A/B` separator as SPDX `A OR B`."""
    return re.sub(r"\s*/\s*", " OR ", expression)


def groups(expression: str) -> list[list[str]]:
    """Splits a canonical SPDX expression into AND-groups of OR-alternatives.

    Handles the shapes crates.io actually uses: `A OR B`, `A AND B` and one
    level of parentheses around an OR group. Anything deeper is a new shape
    and gets refused by the ALLOWED check when its tokens fail.
    """
    result = []
    for part in expression.split(" AND "):
        part = part.strip().strip("()")
        result.append([a.strip() for a in re.split(r"\s+OR\s+", part)])
    return result


def crate_license_files(directory: Path) -> list[Path]:
    return sorted(p for p in directory.iterdir() if p.is_file() and LICENSE_FILE.match(p.name))


def needs_notice(expression: str) -> bool:
    return any(not (set(g) & NOTICE_FREE) for g in groups(expression))


def render() -> str:
    metadata = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--locked"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    workspace = set(metadata["workspace_members"])
    # Every package in Cargo.lock, not only the ones the default resolve
    # activates, so an optional dependency is reviewed before a feature turns
    # it on.
    crates = sorted(
        (p for p in metadata["packages"] if p["id"] not in workspace),
        key=lambda p: (p["name"], p["version"]),
    )

    problems = []
    for crate in crates:
        expression = crate.get("license")
        if not expression:
            problems.append(f"{crate['name']} {crate['version']}: no license expression")
            continue
        expression = crate["license"] = canonical(expression)
        unknown = {a for g in groups(expression) for a in g} - ALLOWED
        if unknown:
            problems.append(f"{crate['name']} {crate['version']}: {expression} (not allowed: {sorted(unknown)})")
        directory = Path(crate["manifest_path"]).parent
        if any(p.name.upper().startswith("NOTICE") for p in crate_license_files(directory)):
            problems.append(f"{crate['name']} {crate['version']}: ships a NOTICE file; carry it in NOTICE")
    if problems:
        sys.exit("refused:\n  " + "\n  ".join(problems))

    lines = [
        "# Third-party crates",
        "",
        "Generated by `python3 tools/third_party.py` from Cargo.lock; `just gate` fails",
        "when this file is stale. Rook's own crates are Apache-2.0 (LICENSE). Every",
        "crate below is taken under its Apache-2.0 option when one is offered. The",
        "license texts that a binary distribution must carry follow the table.",
        "",
        f"{len(crates)} crates.",
        "",
        "| crate | version | license | source |",
        "|---|---|---|---|",
    ]
    for crate in crates:
        source = crate.get("repository") or crate.get("source") or ""
        lines.append(f"| {crate['name']} | {crate['version']} | {crate['license']} | {source} |")

    lines += ["", "## License texts", ""]
    for crate in crates:
        if not needs_notice(crate["license"]):
            continue
        directory = Path(crate["manifest_path"]).parent
        files = crate_license_files(directory)
        if not files:
            sys.exit(f"refused: {crate['name']} {crate['version']} needs a notice and ships no license file")
        lines.append(f"### {crate['name']} {crate['version']} ({crate['license']})")
        lines.append("")
        for path in files:
            lines.append(f"`{path.name}`")
            lines.append("")
            lines.append("```text")
            lines.append(path.read_text(encoding="utf-8").rstrip("\n"))
            lines.append("```")
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if argv == ["--check"]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.name} is stale; run python3 tools/third_party.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT.name} is current")
        return 0
    if argv:
        print(__doc__, file=sys.stderr)
        return 2
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
